version: '3.8'

services:
  pipeline_random:
    build:
      context: .
      dockerfile: ./src/pipelines/random/Dockerfile

    volumes:
      - ./mlflow/artifacts:/app/mlflow/artifacts
      - ./mlflow:/app/mlflow/
    env_file:
      - .env
      - ./src/pipelines/random/pipeline_params.env
    environment:
      - PIPELINE_NAME=RandomRecommender
  
  # pipeline_svd:
  #   build:
  #     context: .
  #     dockerfile: ./src/pipelines/pipeline_svd/
  #   volumes:
  #     - ./mlflow/artifacts:/app/mlflow/artifacts
  #     - ./mlflow:/app/mlflow/
  #   env_file:
  #     - .env
  #   environment:
  #     - PIPELINE_NAME=SVD

  # pipeline_popularity:
  #   build:
  #     context: .
  #     dockerfile: ./src/pipelines/popularity  
  #   volumes:
  #     - ./mlflow/artifacts:/app/mlflow/artifacts
  #     - ./mlflow:/app/mlflow/
  #   env_file:
  #     - .env
  #   environment:
  #     - PIPELINE_NAME=PopularityRecommender

  ftp-server:
    image: stilliard/pure-ftpd:latest
    container_name: ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftp/data:/home/ftpusers
    env_file:
      - .env
    restart: always


  mlflow-server:
    build:
      context: .
      dockerfile: DockerfileMlflow
    expose:
      - "5001"
    ports:
      - "5001:5000"
    env_file:
      - .env
    command: mlflow server --backend-store-uri ${BACKEND_STORE_URI} --default-artifact-root ftp://${FTP_USER_NAME}:${FTP_USER_PASS}@${FTP_HOST}/ --host 0.0.0.0 --port 5000
    restart: always
    volumes:
      - ./mlflow:/work/mlflow # Mount the SQLite database

  db:
    image: ankane/pgvector
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Mount the database data and tables

      
volumes:
  pgdata: