[tool.poetry]
name = "recommendation-practice"
version = "0.1.0"
description = ""
authors = ["PH <phlin@example.com>"]
packages = [{include = "datareader"},{include = "utils"}, {include = "table_models"}]


[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.25"
scikit-surprise = "^1.1.4"
ipykernel = "^6.29.5"
pandas = "^2.2.2"
mlflow = "^2.14.2"
pydantic = "^2.8.2"
joblib = "^1.4.2"
pgvector = "^0.3.0"
psycopg2-binary = "^2.9.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
